import type { Holding } from "./types";

export const HOLDINGS: Holding[] = [
	{
		particulars: "HDFC Bank",
		purchasePrice: 1490,
		qty: 50,
		exchange: "NSE",
		symbol: "HDFCBANK.NS",
		sector: "Financial Sector",
	},
	{
		particulars: "Bajaj Finance",
		purchasePrice: 6466,
		qty: 15,
		exchange: "NSE",
		symbol: "BAJFINANCE.NS",
		sector: "Financial Sector",
	},
	{
		particulars: "ICICI Bank",
		purchasePrice: 780,
		qty: 84,
		exchange: "BSE",
		symbol: "532174.BO",
		sector: "Financial Sector",
	},
	{
		particulars: "Bajaj Housing",
		purchasePrice: 130,
		qty: 504,
		exchange: "BSE",
		symbol: "544252.BO",
		sector: "Financial Sector",
	},
	{
		particulars: "Savani Financials",
		purchasePrice: 24,
		qty: 1080,
		exchange: "BSE",
		symbol: "511577.BO",
		sector: "Financial Sector",
	},
	{
		particulars: "Affle India",
		purchasePrice: 1151,
		qty: 50,
		exchange: "NSE",
		symbol: "AFFLE.NS",
		sector: "Tech Sector",
	},
	{
		particulars: "LTI Mindtree",
		purchasePrice: 4775,
		qty: 16,
		exchange: "NSE",
		symbol: "LTIM.NS",
		sector: "Tech Sector",
	},
	{
		particulars: "KPIT Tech",
		purchasePrice: 672,
		qty: 61,
		exchange: "BSE",
		symbol: "542651.BO",
		sector: "Tech Sector",
	},
	{
		particulars: "Tata Tech",
		purchasePrice: 1072,
		qty: 63,
		exchange: "BSE",
		symbol: "544028.BO",
		sector: "Tech Sector",
	},
	{
		particulars: "BLS E-Services",
		purchasePrice: 232,
		qty: 191,
		exchange: "BSE",
		symbol: "544107.BO",
		sector: "Tech Sector",
	},
	{
		particulars: "Tanla",
		purchasePrice: 1134,
		qty: 45,
		exchange: "BSE",
		symbol: "532790.BO",
		sector: "Tech Sector",
	},
	{
		particulars: "Dmart",
		purchasePrice: 3777,
		qty: 27,
		exchange: "NSE",
		symbol: "DMART.NS",
		sector: "Consumer",
	},
	{
		particulars: "Tata Consumer",
		purchasePrice: 845,
		qty: 90,
		exchange: "BSE",
		symbol: "532540.BO",
		sector: "Consumer",
	},
	{
		particulars: "Pidilite",
		purchasePrice: 2376,
		qty: 36,
		exchange: "BSE",
		symbol: "500331.BO",
		sector: "Consumer",
	},
	{
		particulars: "Tata Power",
		purchasePrice: 224,
		qty: 225,
		exchange: "BSE",
		symbol: "500400.BO",
		sector: "Power",
	},
	{
		particulars: "KPI Green",
		purchasePrice: 875,
		qty: 50,
		exchange: "BSE",
		symbol: "542323.BO",
		sector: "Power",
	},
	{
		particulars: "Suzlon",
		purchasePrice: 44,
		qty: 450,
		exchange: "BSE",
		symbol: "532667.BO",
		sector: "Power",
	},
	{
		particulars: "Gensol",
		purchasePrice: 998,
		qty: 45,
		exchange: "BSE",
		symbol: "542851.BO",
		sector: "Power",
	},
	{
		particulars: "Hariom Pipes",
		purchasePrice: 580,
		qty: 60,
		exchange: "BSE",
		symbol: "543517.BO",
		sector: "Pipe Sector",
	},
	{
		particulars: "Astral",
		purchasePrice: 1517,
		qty: 56,
		exchange: "NSE",
		symbol: "ASTRAL.NS",
		sector: "Pipe Sector",
	},
	{
		particulars: "Polycab",
		purchasePrice: 2818,
		qty: 28,
		exchange: "BSE",
		symbol: "542652.BO",
		sector: "Pipe Sector",
	},
	{
		particulars: "Clean Science",
		purchasePrice: 1610,
		qty: 32,
		exchange: "BSE",
		symbol: "543318.BO",
		sector: "Others",
	},
	{
		particulars: "Deepak Nitrite",
		purchasePrice: 2248,
		qty: 27,
		exchange: "BSE",
		symbol: "506401.BO",
		sector: "Others",
	},
	{
		particulars: "Fine Organic",
		purchasePrice: 4284,
		qty: 16,
		exchange: "BSE",
		symbol: "541557.BO",
		sector: "Others",
	},
	{
		particulars: "Gravita",
		purchasePrice: 2037,
		qty: 8,
		exchange: "BSE",
		symbol: "533282.BO",
		sector: "Others",
	},
	{
		particulars: "SBI Life",
		purchasePrice: 1197,
		qty: 49,
		exchange: "BSE",
		symbol: "540719.BO",
		sector: "Others",
	},
];
